apimServiceName: prod-apim-cicd
namedValues: 
  - name: plainvalue
    properties:
      displayName: plainvalue
      value: "https://www.PROD.search2.com"
  - name: secret
      properties:
      displayName: secret
      value: "PRODSecret"
loggers:
diagnostics:
backends:
apis:
